#POSTGRESQL DATABASE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learning
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

#JWT
app:
  jwt:
    secret: /qFVTLxfWt7UEwGOLoQ8JqKxlJuOsR0dpPm5ChPdGLo=
    expiration: 864000000

  #SETUP
  setup:
    admin:
      email: admin@gmail.com